### ISSUE TITLE
‘std::function’ issue on geant4 virtual machine version 11.0

### ISSUE THREAD

**Issue by LasDes** [dr4kan/EcoMug#1]
I am trying to use EcoMug.h in the geant4 virtual machine v11.0 from "Geant4 Virtual Machine – G4VM with RockyLinux 8.5 Geant4 "
and I am getting this error using c++ 11

`home/local1/Desktop/t4_rpc/include/EcoMug.h:100:8: error: ‘function’ in namespace ‘std’ does not name a template type
   std::function<double(double, double)> mFunc;`

`/home/local1/Desktop/t4_rpc/include/EcoMug.h:100:3: note: ‘std::function’ is defined in header ‘<functional>’; did you forget to ‘#include <functional>’?
/home/local1/Desktop/t4_rpc/include/EcoMug.h:29:1:
+#include <functional>`

**Comment by dr4kan** [comment]
Hi, 

thank you for pointing it out. Can you please try version 1.3.1?

Cheers,
Davide.

**Comment by LasDes** [comment]
sorry for the delayed response, but i fixed.
The solution was to download the 1.3.1 version and add #include "functional"  into the header inside Ecomug.h
