### ISSUE TITLE
Question on theta / zenith angle implementation

### ISSUE THREAD

**Issue by Martin-SF** [dr4kan/EcoMug#5]
Hi there! 
I have had some problems understanding how the theta angle is "understood" in EcoMug.

For example, I was expecting to give it the theta angle as a zenith angle, range from 9° to 11° and get back zenith from 9 - 11° or 191° to 189° or 179° to 181°.
But I get 99° to 101°. Somewhere the theta angle is understood as an altitude angle and sometimes as an azimuth angle, at least as I understand it?

At least for my use case, I just want to have azimuth angles (and a 180° flip at the end to point it down, for the simulation). I also tried to convert the angles, but that somehow failed too. So I thought I would give it a try here!

If you could explain it to me, I would be very grateful! 
(I'm still on v1.3.1, but at least from what I've seen, everything regarding theta calculations hasn't been touched in the newer versions?)

Thanks in advance!
Martin

**Comment by dr4kan** [comment]
Hi,

EcoMug expects the theta angle to be defined between 0 and 90 deg, where 0 is vertical and 90 ded is horizontal. Take a look at how the reference frame is defined by looking at our paper: https://doi.org/10.1016/j.nima.2021.165732
What EcoMug outputs is based on that reference frame. Theta values more than 90 deg are, therefore, meaningless as they would correspond to muons coming from below ground.

Best,
Davide.

**Comment by Martin-SF** [comment]
Hey Davide, thanks for the clarification! I made some errors on my side along the way. Everything works now as expected.
