### ISSUE TITLE
Question on Theta distribution

### ISSUE THREAD

**Issue by crispsssy** [dr4kan/EcoMug#6]
Hi!

Maybe it's a stupid question, I tried to generate some samples, then I drew Momentum, theta, and phi distributions. But in the theta distribution peak is not Pi, why?
<img width="686" alt="截屏2024-11-14 17 45 52" src="https://github.com/user-attachments/assets/1f6588fd-198f-469b-ab6b-e66d7db62340">

**Comment by dr4kan** [comment]
Why do you expect it to be peaked at pi? Please take a look at the following paper (where ecomug has been presented) https://www.sciencedirect.com/science/article/pii/S0168900221007178. There you will find the definitions of the differential fluxes used in the code. For example, you will notice that J'z (that is the differential flux crossing a horizontal surface) is actually 0 for theta = 0 (or equivalently for theta = pi).

**Comment by crispsssy** [comment]
Thank you for the reply, I read your paper and saw the calculation in it. It's not so intuitive to me to consider that there is no muon coming from the direction that perpendicular to ground surface (where J'z is 0)...

In the figure 1 that plot shows differential flux peak stays near theta = 0, but after in the calculation that flux become 0 for the same region, can you please remind me what is the difference between these two "theta"?

**Comment by dr4kan** [comment]
I'll try to get you to visualize this better with a simplification. Consider a half-sphere and put yourself in the center. Now, choose a generic value for theta and consider all the points on the half-sphere that can see you under that theta angle. It's trivial to see that those (inifinite) points will lay on a circle of radius: R sin(theta). If you choose theta = 0, only one point will exist that can see you under that angle...

**Comment by crispsssy** [comment]
Emmmmm....I try to understand your description, can you please make me clear that what is the definition of "theta" in your paper and also in the code `GetGenerationTheta()`? Is that the angle between Z axis (vertical direction that perpendicular to the ground) and muon direction, just the same as spherical coordinate?

**Comment by crispsssy** [comment]
I think I understood your explanation, thank you very much!!!
